Create Плюсы_2Лаба.h
ViktorOneLove/cPlusPlus pull request #1
Opened 2020-04-01 20:44 UTC by JUDGEViktor

2020-04-02 06:02 UTC, Gandy123 commented on Плюсы_2Лаба.h
> +
вот так не надо делать. зачем прятать в private и давать Get ? убирайте и переносите все те места где вы с getGoord работаете в vector

2020-04-02 06:03 UTC, Gandy123 commented on Плюсы_2Лаба.h
> +
оператор +

2020-04-02 06:03 UTC, Gandy123 commented on Плюсы_2Лаба.h
> +
глобальную переменную не надо в h

2020-04-02 06:03 UTC, Gandy123 commented on Плюсы_2Лаба.h
> +coordinates Vector::GetCOORD() {
описание методов лучше в С++

2020-04-02 06:04 UTC, Gandy123 commented on Плюсы_2Лаба.h
> +
тоже самое что и выше

2020-04-02 06:04 UTC, Gandy123 requested changes
done

2020-04-03 05:56 UTC, Gandy123 commented on Плюсы_2Лаба.h
> +
не надо coords наружу вытаскивать - лучше тот код который с ними работает снаружи перенесите в класс

2020-04-03 05:57 UTC, Gandy123 commented on Плюсы_2Лаба.h
> +
лучше переименовать в collision_result или что-то такое

2020-04-03 05:57 UTC, Gandy123 commented on Плюсы_2Лаба.h
> +
и вектор и координаты надо private и код по работе с ними перенести в класс

2020-04-03 05:58 UTC, Gandy123 requested changes
done

2020-04-06 06:00 UTC, Gandy123 commented on Плюсы_2Лаба.h
> +	friend class Mob;
friend не надо.  зачем вам friend ?

2020-04-06 06:01 UTC, Gandy123 commented on Плюсы_2Лаба.h
> +
это не сделали

2020-04-06 06:02 UTC, Gandy123 requested changes
надо friend убрать

2020-04-06 07:21 UTC, JUDGEViktor commented
класс friend, чтобы обращаться к приватным координатам вектора, без использования функции Get(), или использование таких функций приемлемо внутри класса? Тогда friend действительно не нужен.

  
>Понедельник, 6 апреля 2020, 9:00 +03:00 от Andrey <notifications@github.com>:
> 
> 
>@Gandy123 commented on this pull request.
>----------------------------------------------------------------------
>In  Плюсы_2Лаба.h :
>>  	}
>
>+
>
>+	friend class Mob;
>
>
>friend не надо. зачем вам friend ?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Виктор Герасименко
 

2020-04-17 17:26 UTC, closed without merging

2020-04-17 17:26 UTC, JUDGEViktor commented
Complete second lab