Paint
ViktorOneLove/cPlusPlus pull request #11
Opened 2020-06-06 19:59 UTC by JUDGEViktor

First commit

2020-06-08 08:47 UTC, Gandy123 commented on BrushAbstract.h
> +
vector<vector лучше как-то назвать используя using

2020-06-08 08:48 UTC, Gandy123 commented on Circle.h
> +
классы лучше по ссылке передавать, чтобы избежать копирования лишнего

2020-06-08 08:49 UTC, Gandy123 commented on Libraries.h
> +
в С++не надо typedef можно просто писать structor colorRGB {}

2020-06-08 08:49 UTC, Gandy123 requested changes
done

2020-06-11 07:19 UTC, Gandy123 commented on Circle.h
> +
> классы лучше по ссылке передавать, чтобы избежать копирования лишнего
не сделали и vector<vector здесь не заменили на pixels

2020-06-11 07:20 UTC, Gandy123 requested changes
один комментарий не учли или файл не убрали из pull request-а

2020-06-11 07:51 UTC, JUDGEViktor commented on Circle.h
> +
Просмотрел. Удалил этот файл.

2020-06-11 07:53 UTC, JUDGEViktor commented on Libraries.h
> +
Исправлено

2020-06-15 07:43 UTC, closed without merging